import { Campaign, Asset, Folder, Comment, Deliverable } from "./types";

export const campaigns: Campaign[] = [
  {
    id: "camp-1",
    name: "Summer Refresh 2026",
    client: "Dryp Beverages",
    brand: "Dryp",
    status: "review",
    dueDate: "2026-04-28",
    thumbnail: "/placeholder-campaign-1.jpg",
    assetsCount: 34,
    progress: 72,
    platforms: ["Instagram", "TikTok", "YouTube", "TV"],
  },
  {
    id: "camp-2",
    name: "Launch Campaign — AquaPure",
    client: "AquaPure Co.",
    brand: "AquaPure",
    status: "production",
    dueDate: "2026-05-15",
    thumbnail: "/placeholder-campaign-2.jpg",
    assetsCount: 18,
    progress: 35,
    platforms: ["Facebook", "Instagram", "YouTube"],
  },
  {
    id: "camp-3",
    name: "Black Friday — Flash Deals",
    client: "TechVault",
    brand: "TechVault",
    status: "brief",
    dueDate: "2026-11-20",
    thumbnail: "/placeholder-campaign-3.jpg",
    assetsCount: 0,
    progress: 5,
    platforms: ["Google Ads", "Meta", "TikTok", "Email"],
  },
  {
    id: "camp-4",
    name: "Brand Awareness Q2",
    client: "Dryp Beverages",
    brand: "Dryp",
    status: "approved",
    dueDate: "2026-04-10",
    thumbnail: "/placeholder-campaign-4.jpg",
    assetsCount: 52,
    progress: 95,
    platforms: ["TV", "YouTube", "Cinema"],
  },
  {
    id: "camp-5",
    name: "Holiday Gift Guide",
    client: "LuxeBox",
    brand: "LuxeBox",
    status: "delivered",
    dueDate: "2025-12-01",
    thumbnail: "/placeholder-campaign-5.jpg",
    assetsCount: 28,
    progress: 100,
    platforms: ["Instagram", "Pinterest", "Email"],
  },
];

export const folders: Folder[] = [
  { id: "f-1", name: "Raw Footage", icon: "film", count: 19 },
  { id: "f-2", name: "Graphics", icon: "image", count: 6 },
  { id: "f-3", name: "Sound & Music", icon: "music", count: 9 },
  { id: "f-4", name: "Edits", icon: "scissors", count: 8 },
  { id: "f-5", name: "Final Renders", icon: "check-circle", count: 4 },
  { id: "f-6", name: "Client Briefs", icon: "file-text", count: 3 },
];

export const assets: Asset[] = [
  {
    id: "a-1",
    name: "Hero_Shot_Pool_V3.mov",
    type: "video",
    folder: "f-1",
    thumbnail: "",
    duration: "00:26",
    size: "186 MB",
    uploadedBy: "Alex M.",
    uploadedAt: "2026-04-12",
    status: "review",
    version: 3,
    comments: 5,
    width: 3840,
    height: 2160,
    format: "ProRes 422",
  },
  {
    id: "a-2",
    name: "Product_Close_Up_B.mov",
    type: "video",
    folder: "f-1",
    thumbnail: "",
    duration: "00:14",
    size: "94 MB",
    uploadedBy: "Alex M.",
    uploadedAt: "2026-04-12",
    status: "approved",
    version: 2,
    comments: 2,
    width: 3840,
    height: 2160,
    format: "ProRes 422",
  },
  {
    id: "a-3",
    name: "Lifestyle_Beach_Sunset.mov",
    type: "video",
    folder: "f-1",
    thumbnail: "",
    duration: "00:19",
    size: "142 MB",
    uploadedBy: "Maria D.",
    uploadedAt: "2026-04-11",
    status: "review",
    version: 1,
    comments: 8,
    width: 3840,
    height: 2160,
    format: "ProRes 422",
  },
  {
    id: "a-4",
    name: "Drone_Aerial_Coast.mov",
    type: "video",
    folder: "f-1",
    thumbnail: "",
    duration: "00:32",
    size: "248 MB",
    uploadedBy: "Alex M.",
    uploadedAt: "2026-04-10",
    status: "production",
    version: 1,
    comments: 0,
    width: 3840,
    height: 2160,
    format: "ProRes 422 HQ",
  },
  {
    id: "a-5",
    name: "Dryp_Logo_Black.ai",
    type: "image",
    folder: "f-2",
    thumbnail: "",
    size: "1.2 MB",
    uploadedBy: "Diana P.",
    uploadedAt: "2026-04-08",
    status: "approved",
    version: 1,
    comments: 0,
    format: "Illustrator",
  },
  {
    id: "a-6",
    name: "Product_Family_Shot.png",
    type: "image",
    folder: "f-2",
    thumbnail: "",
    size: "4.8 MB",
    uploadedBy: "Diana P.",
    uploadedAt: "2026-04-09",
    status: "review",
    version: 2,
    comments: 3,
    width: 4000,
    height: 3000,
    format: "PNG",
  },
  {
    id: "a-7",
    name: "Summer_Vibe_Track.wav",
    type: "audio",
    folder: "f-3",
    thumbnail: "",
    duration: "02:45",
    size: "28 MB",
    uploadedBy: "Radu S.",
    uploadedAt: "2026-04-07",
    status: "approved",
    version: 1,
    comments: 1,
    format: "WAV 48kHz",
  },
  {
    id: "a-8",
    name: "SFX_Water_Splash.wav",
    type: "audio",
    folder: "f-3",
    thumbnail: "",
    duration: "00:03",
    size: "1.5 MB",
    uploadedBy: "Radu S.",
    uploadedAt: "2026-04-07",
    status: "approved",
    version: 1,
    comments: 0,
    format: "WAV 48kHz",
  },
  {
    id: "a-9",
    name: "TikTok_Cut_15s_V2.mp4",
    type: "video",
    folder: "f-4",
    thumbnail: "",
    duration: "00:15",
    size: "18 MB",
    uploadedBy: "Alex M.",
    uploadedAt: "2026-04-13",
    status: "review",
    version: 2,
    comments: 4,
    width: 1080,
    height: 1920,
    format: "H.264",
  },
  {
    id: "a-10",
    name: "YouTube_Pre-Roll_30s.mp4",
    type: "video",
    folder: "f-4",
    thumbnail: "",
    duration: "00:30",
    size: "42 MB",
    uploadedBy: "Alex M.",
    uploadedAt: "2026-04-13",
    status: "revision",
    version: 3,
    comments: 7,
    width: 1920,
    height: 1080,
    format: "H.264",
  },
  {
    id: "a-11",
    name: "Instagram_Story_V1.mp4",
    type: "video",
    folder: "f-4",
    thumbnail: "",
    duration: "00:09",
    size: "12 MB",
    uploadedBy: "Maria D.",
    uploadedAt: "2026-04-14",
    status: "production",
    version: 1,
    comments: 0,
    width: 1080,
    height: 1920,
    format: "H.264",
  },
  {
    id: "a-12",
    name: "TV_Spot_30s_Final.mov",
    type: "video",
    folder: "f-5",
    thumbnail: "",
    duration: "00:30",
    size: "320 MB",
    uploadedBy: "Alex M.",
    uploadedAt: "2026-04-14",
    status: "approved",
    version: 5,
    comments: 12,
    width: 1920,
    height: 1080,
    format: "ProRes 4444",
  },
  {
    id: "a-13",
    name: "Campaign_Brief_v2.pdf",
    type: "document",
    folder: "f-6",
    thumbnail: "",
    size: "2.3 MB",
    uploadedBy: "Client",
    uploadedAt: "2026-04-01",
    status: "approved",
    version: 2,
    comments: 1,
    format: "PDF",
  },
];

export const comments: Comment[] = [
  {
    id: "c-1",
    author: "Sarah (Client)",
    avatar: "SC",
    text: "The color grading on this shot is perfect. Love the teal tones in the water.",
    timestamp: "2026-04-13 14:32",
    timecode: "00:08",
    visibility: "public",
    resolved: false,
  },
  {
    id: "c-2",
    author: "Alex M.",
    avatar: "AM",
    text: "Can we try a slightly warmer grade here? The product label gets lost in the cool tones.",
    timestamp: "2026-04-13 15:10",
    timecode: "00:12",
    visibility: "team",
    resolved: false,
    replies: [
      {
        id: "c-2-1",
        author: "Maria D.",
        avatar: "MD",
        text: "Agreed — I'll push the highlights warmer and add a subtle vignette to draw the eye.",
        timestamp: "2026-04-13 15:25",
        visibility: "team",
        resolved: false,
      },
    ],
  },
  {
    id: "c-3",
    author: "Sarah (Client)",
    avatar: "SC",
    text: "The transition at this point feels too fast. Can we slow it down to 1.5s?",
    timestamp: "2026-04-12 10:05",
    timecode: "00:18",
    visibility: "public",
    resolved: true,
  },
  {
    id: "c-4",
    author: "Diana P.",
    avatar: "DP",
    text: "Logo placement needs to be 20% larger per brand guidelines. Also shift it 10px left.",
    timestamp: "2026-04-13 09:45",
    timecode: "00:24",
    visibility: "team",
    resolved: false,
  },
  {
    id: "c-5",
    author: "Radu S.",
    avatar: "RS",
    text: "Audio levels spike here — need to normalize the splash SFX to -6dB.",
    timestamp: "2026-04-13 11:20",
    timecode: "00:15",
    visibility: "team",
    resolved: false,
  },
];

export const deliverables: Deliverable[] = [
  { id: "d-1", platform: "TikTok", format: "MP4 / H.264", dimensions: "1080×1920", duration: "15s", status: "ready", assetId: "a-9" },
  { id: "d-2", platform: "Instagram Reels", format: "MP4 / H.264", dimensions: "1080×1920", duration: "30s", status: "rendering" },
  { id: "d-3", platform: "Instagram Story", format: "MP4 / H.264", dimensions: "1080×1920", duration: "9s", status: "ready", assetId: "a-11" },
  { id: "d-4", platform: "YouTube Pre-Roll", format: "MP4 / H.264", dimensions: "1920×1080", duration: "30s", status: "pending", assetId: "a-10" },
  { id: "d-5", platform: "YouTube Bumper", format: "MP4 / H.264", dimensions: "1920×1080", duration: "6s", status: "pending" },
  { id: "d-6", platform: "Facebook Feed", format: "MP4 / H.264", dimensions: "1080×1080", duration: "15s", status: "pending" },
  { id: "d-7", platform: "TV Broadcast", format: "ProRes 4444", dimensions: "1920×1080", duration: "30s", status: "ready", assetId: "a-12" },
  { id: "d-8", platform: "Cinema", format: "DCP / JPEG2000", dimensions: "2048×858", duration: "30s", status: "pending" },
  { id: "d-9", platform: "Google Display", format: "MP4 / H.264", dimensions: "300×250", duration: "15s", status: "pending" },
  { id: "d-10", platform: "Meta Carousel", format: "MP4 / H.264", dimensions: "1080×1080", duration: "10s ×5", status: "pending" },
];
